name: WildExtras
main: org.hopto.thewild.WildExtras.WildExtras
version: 0.3
depends: [Essentials, dynmap, Stats, GroupManager]
commands:
   pvpon:
      description: Removes pvp spam protection!
      usage: /pvpon
      permission: wildextras.pvpon
      permission-message: You can't do that!
   clearpvpcount:
      description: Removes for 1hour count reset!
      usage: /clearpvpcount
      permission: wildextras.clearpvpcount
      permission-message: You can't do that!
   arrowclear:
      description: Removes all arrows, from all worlds!
      usage: /arrowclear
      permission: wildextras.arrowclear
      permission-message: You can't do that!
   va:
      description: Accept a mod visit
      usage: /va
   visit:
      description: Mod only
      usage: /visit <player>
      permission: wildextras.visit
      permission-message: You can't do that!
   endvisit:
      description: Mod only
      usage: /endvisit
      permission: wildextras.visit
      permission-message: You can't do that!
   makevisitinv:
      description: Mod only
      usage: /makevisitinv 
      permission: wildextras.makevisitinv
      permission-message: You can't do that!
permissions:
    wildextras.*:
        description: Gives access to all wildextras commands
        children:
            wildextras.arrowclear: true
            wildextras.visit: true
    wildextras.arrowclear:
        description: Clears all arrows in the world
        default: op
    wildextras.visit:
        description: See!
        default: op
    wildextras.makevisitinv:
        description: Create the visit inventory
        default: op
